// ==UserScript==
// @name         ScreenConnect Timeout
// @namespace    http://tampermonkey.net/
// @version      1.0.4
// @description  Color old chat with red + rainbow for dev machine
// @author       BigYass
// @match        https://*.fr/Host
// @include      /^https://connect\.[^/]+\.fr\/Host$/
// @icon         data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBmaWxsPSIjZTY2MjMyIiBkPSJNMTAgM3EtLjQyNSAwLS43MTItLjI4OFQ5IDJ0LjI4OC0uNzEyVDEwIDFoNHEuNDI1IDAgLjcxMy4yODhUMTUgMnQtLjI4OC43MTNUMTQgM3ptMi43MTMgMTAuNzEzUTEzIDEzLjQyNSAxMyAxM1Y5cTAtLjQyNS0uMjg4LS43MTJUMTIgOHQtLjcxMi4yODhUMTEgOXY0cTAgLjQyNS4yODguNzEzVDEyIDE0dC43MTMtLjI4OG0tNC4yIDcuNTc2cS0xLjYzOC0uNzEzLTIuODYzLTEuOTM4dC0xLjkzNy0yLjg2M1QzIDEzdC43MTMtMy40ODhUNS42NSA2LjY1dDIuODYzLTEuOTM3VDEyIDRxMS41NSAwIDIuOTc1LjV0Mi42NzUgMS40NWwuNy0uN3EuMjc1LS4yNzUuNy0uMjc1dC43LjI3NXQuMjc1Ljd0LS4yNzUuN2wtLjcuN1EyMCA4LjYgMjAuNSAxMC4wMjVUMjEgMTNxMCAxLjg1LS43MTMgMy40ODhUMTguMzUgMTkuMzV0LTIuODYzIDEuOTM4VDEyIDIydC0zLjQ4OC0uNzEybTguNDM4LTMuMzM4UTE5IDE1LjkgMTkgMTN0LTIuMDUtNC45NVQxMiA2VDcuMDUgOC4wNVQ1IDEzdDIuMDUgNC45NVQxMiAyMHQ0Ljk1LTIuMDVNMTIgMTMiLz48L3N2Zz4=
// @grant        none
// @updateURL    https://raw.githubusercontent.com/BigYass/itg.tampermonkey_scripts/main/screen_timeout.user.js
// @downloadURL  https://raw.githubusercontent.com/BigYass/itg.tampermonkey_scripts/main/screen_timeout.user.js
// ==/UserScript==
!function(){"use strict";const t=()=>{const t=document.querySelectorAll("div.Host");t&&0!==t.length&&t.forEach(t=>{const e=t.closest("tr");if(!e)return;const n=e.querySelector("h3.SessionTitle");if(!n)return;if("71c9d3b2"===(t=>{let e=0;for(let n=0;n<t.length;n++)e=(e<<5)-e+t.charCodeAt(n),e|=0;return Math.abs(e).toString(16)})((n.textContent||"").trim()))return void n.classList.add("rainbow-text");const o=t.querySelector("p.Description");if(!o)return;const r=(o.textContent||"").split(/[-)]/),l=(t=>{const e=String(t||"").match(/^\s*(?:(\d+)h)?\s*(?:(\d+)m)?\s*$/i);if(!e)return NaN;const n=e[1]?parseInt(e[1],10):0,o=e[2]?parseInt(e[2],10):0;return e[1]||e[2]?60*n+o:NaN})((r.length>0?r[r.length-1]:"").trim());var s;Number.isNaN(l)||(l>30?(s=n)&&"red"!==s.style.color&&(s.style.color="red"):(t=>{t&&t.style.color&&t.style.removeProperty("color")})(n))})},e=()=>{t(),window.setTimeout(e,1e3)};let n=null;const o=new MutationObserver(()=>{n||(n=window.setTimeout(()=>{n=null,t()},150))}),r=()=>{(()=>{if(document.getElementById("itg-rainbow-style"))return;const t=document.createElement("style");t.id="itg-rainbow-style",t.textContent="\n      .rainbow-text {\n        animation: colorFloat 2s linear infinite;\n        will-change: color;\n      }\n\n      @keyframes colorFloat {\n        0%   { color: hsla(0, 94%, 74%, 1.00); }\n        25%  { color: hsla(90, 87%, 73%, 1.00); }\n        50%  { color: hsla(180, 97%, 85%, 1.00); }\n        75%  { color: hsla(270, 100%, 79%, 1.00); }\n        100% { color: hsla(0, 94%, 74%, 1.00); }\n      }\n    ",document.head.appendChild(t)})(),t(),o.observe(document.body,{childList:!0,subtree:!0,attributes:!0}),e()};"loading"===document.readyState?document.addEventListener("DOMContentLoaded",r,{once:!0}):r()}();